Revert "Fix error: implicit declaration of function 'get_cpu_idle_time_us'"
This reverts commit d8c38ad7de1de8b354cfe2384fc9f22cbaced953.

Revert "sched/accounting: Change cpustat fields to an array"

This reverts commit 774b0884ef3062b7fdbf07f82b8e46210198b65f.